FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ProjectManagementAPP/ProjectManagementAPP.csproj", "ProjectManagementAPP/"]
RUN dotnet restore "ProjectManagementAPP/ProjectManagementAPP.csproj"
COPY . .
WORKDIR "/src/ProjectManagementAPP"
RUN dotnet build "ProjectManagementAPP.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ProjectManagementAPP.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ProjectManagementAPP.dll"]
